apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisstudy-pgadmin-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  ports:
  - protocol: TCP
    port: 5050
    targetPort: http
  selector:
    component: redisstudy-pgadmin
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisstudy-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redisstudy-pgadmin
  template:
    metadata:
      labels:
        component: redisstudy-pgadmin
    spec:
      containers:
        - name: redisstudy-pgadmin
          image: thajeztah/pgadmin4
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: "sa"
          volumeMounts:
            - name: redisstudy-pgadmin-volume
              mountPath: /pgadmin
      volumes:
        - name: redisstudy-pgadmin-volume
          persistentVolumeClaim:
            claimName: redisstudy-pgadmin-volume
