apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisstudy-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redisstudy-postgres
  template:
    metadata:
      labels:
        component: redisstudy-postgres
    spec:
      containers:
        - name: redisstudy-postgres
          image: postgres:10.13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: sa
          volumeMounts:
            - name: redisstudy-postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: redisstudy-postgres-volume
          persistentVolumeClaim:
            claimName: redisstudy-postgres-volume
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    component: redisstudy-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisstudy-postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
