apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    component: redisstudy-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisstudy-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redisstudy-redis
  template:
    metadata:
      labels:
        component: redisstudy-redis
    spec:
      containers:
        - name: redisstudy-redis
          image: docker-registry:5000/redisstudy-redis:latest
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              value: apfel
