apiVersion: v1
kind: Service
metadata:
  name: webservice
  namespace: redisstudy
spec:
  type: ClusterIP
  selector:
    component: webservice
  ports:
  - protocol: TCP
    port: 8400
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  namespace: redisstudy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webservice
  template:
    metadata:
      labels:
        component: webservice
    spec:
      containers:
      - name: webservice
        image: docker-registry:5000/redisstudy-redisstudy:1.1.5-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8400
          protocol: TCP
        env:
        - name: REDISSTUDY_OPTS
          value: -Dspring.profiles.active=k8s
        - name: APP
          value: webservice
        - name: NAMESPACE
          value: redisstudy
        - name: DOMAIN
          value: k8s-test.perit.hu
